import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/******************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-02-24 12:47:46.455 UTC-08:00
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/


    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands

        // @command set_pwm1
        // @property duty_cycle: double
        // @property status: bool
        property var set_pwm1: ({
            "cmd": "set_pwm1",
            "payload": {
                "current": 0.0,
                "status": false
            },
            update: function (current,status) {
                this.set(current,status)
                this.send(this)
            },
            set: function (current,status) {
                this.payload.current = current
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

        // @command set_pwm2
        // @property duty_cycle: double
        // @property status: bool
        property var set_pwm2: ({
            "cmd": "set_pwm2",
            "payload": {
                "voltage": 0.0,
                "status": false
            },
            update: function (voltage,status) {
                this.set(voltage,status)
                this.send(this)
            },
            set: function (voltage,status) {
                this.payload.voltage = voltage
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

        // @command set_pwm3
        // @property duty_cycle: double
        // @property status: bool
        property var set_pwm3: ({
            "cmd": "set_pwm3",
            "payload": {
                "on_time": 0.0,
                "status": false
            },
            update: function (on_time,status) {
                this.set(on_time,status)
                this.send(this)
            },
            set: function (on_time,status) {
                this.payload.on_time = on_time
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

    }
}
