/*
 * Copyright (c) 2018-2022 onsemi.
 *
 * All rights reserved. This software and/or documentation is licensed by onsemi under
 * limited terms and conditions. The terms and conditions pertaining to the software and/or
 * documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf (“onsemi Standard
 * Terms and Conditions of Sale, Section 8 Software”).
 */
import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/******************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-09-02 17:11:57.166 UTC-07:00
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias notifications: notifications
    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    QtObject {
        id: notifications

        // @notification: actual_speed
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject actual_speed: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: target_speed
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject target_speed: QtObject {
            property string caption: ""
            property string unit: ""
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: acceleration
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject acceleration: QtObject {
            property string caption: ""
            property string unit: ""
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 2
            }
        }

        // @notification: board_temp
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject board_temp: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: input_voltage
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject input_voltage: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: title
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject title: QtObject {
            property string caption: "Title"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: subtitle
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject subtitle: QtObject {
            property string caption: "Subtitle"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_1
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_1: QtObject {
            property string caption: "Warning 1"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_2
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_2: QtObject {
            property string caption: "Warning 2"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_3
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_3: QtObject {
            property string caption: "Warning 3"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_4
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_4: QtObject {
            property string caption: "Warning 4"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: status_log
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject status_log: QtObject {
            property string caption: "Status Log"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: run
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject run: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: brake
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject brake: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: direction
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject direction: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: request_params
        property QtObject request_params: QtObject {

            signal notificationFinished()
        }

        // @notification: startup_fault
        property QtObject startup_fault: QtObject {

            signal notificationFinished()
        }

    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands
        // @command pwm_params
        // @property o_mode: int
        // @property dt: int
        // @property min_ls: int
        // @property freq: int
        // @property tr_delay: int
        property var pwm_params: ({
            "cmd": "pwm_params",
            "payload": {
                "o_mode": 0,
                "dt": 0,
                "min_ls": 0,
                "freq": 0,
                "tr_delay": 0
            },
            update: function (o_mode, dt, min_ls, freq, tr_delay) {
                this.set(o_mode, dt, min_ls, freq, tr_delay)
                this.send(this)
            },
            set: function (o_mode, dt, min_ls, freq, tr_delay) {
                this.payload.o_mode = o_mode
                this.payload.dt = dt
                this.payload.min_ls = min_ls
                this.payload.freq = freq
                this.payload.tr_delay = tr_delay
            },
            send: function () { platformInterface.send(this) }
        })

        // @command pid_params
        // @property kp: double
        // @property ki: double
        // @property kd: double
        // @property wd: double
        // @property lim: double
        // @property tau_sys: double
        // @property mode: int
        property var pid_params: ({
            "cmd": "pid_params",
            "payload": {
                "kp": 0,
                "ki": 0,
                "kd": 0,
                "wd": 0,
                "lim": 0,
                "tau_sys": 0,
                "mode": 0
            },
            update: function (kp, ki, kd, wd, lim, tau_sys, mode) {
                this.set(kp, ki, kd, wd, lim, tau_sys, mode)
                this.send(this)
            },
            set: function (kp, ki, kd, wd, lim, tau_sys, mode) {
                this.payload.kp = kp
                this.payload.ki = ki
                this.payload.kd = kd
                this.payload.wd = wd
                this.payload.lim = lim
                this.payload.tau_sys = tau_sys
                this.payload.mode = mode
            },
            send: function () { platformInterface.send(this) }
        })

        // @command motor_params
        // @property rs: double
        // @property ls: double
        // @property jm: double
        // @property jm_load: double
        // @property kv: double
        // @property kv_load: double
        // @property pp: int
        // @property max_rpm: double
        // @property rated_rpm: double
        // @property min_rpm: double
        // @property ke: double
        // @property rated_v: double
        // @property hall_pol: int
        property var motor_params: ({
            "cmd": "motor_params",
            "payload": {
                "rs": 0,
                "ls": 0,
                "jm": 0,
                "jm_load": 0,
                "kv": 0,
                "kv_load": 0,
                "pp": 0,
                "max_rpm": 0,
                "rated_rpm": 0,
                "min_rpm": 0,
                "ke": 0,
                "rated_v": 0,
                "hall_pol": 0
            },
            update: function (rs, ls, jm, jm_load, kv, kv_load, pp, max_rpm, rated_rpm, min_rpm, ke, rated_v, hall_pol) {
                this.set(rs, ls, jm, jm_load, kv, kv_load, pp, max_rpm, rated_rpm, min_rpm, ke, rated_v, hall_pol)
                this.send(this)
            },
            set: function (rs, ls, jm, jm_load, kv, kv_load, pp, max_rpm, rated_rpm, min_rpm, ke, rated_v, hall_pol) {
                this.payload.rs = rs
                this.payload.ls = ls
                this.payload.jm = jm
                this.payload.jm_load = jm_load
                this.payload.kv = kv
                this.payload.kv_load = kv_load
                this.payload.pp = pp
                this.payload.max_rpm = max_rpm
                this.payload.rated_rpm = rated_rpm
                this.payload.min_rpm = min_rpm
                this.payload.ke = ke
                this.payload.rated_v = rated_v
                this.payload.hall_pol = hall_pol
            },
            send: function () { platformInterface.send(this) }
        })

        // @command spd_loop_params
        // @property mode: int
        // @property accel: int
        // @property fs: int
        // @property fspd_filt: int
        property var spd_loop_params: ({
            "cmd": "spd_loop_params",
            "payload": {
                "mode": 0,
                "accel": 0,
                "fs": 0,
                "fspd_filt": 0
            },
            update: function (mode, accel, fs, fspd_filt) {
                this.set(mode, accel, fs, fspd_filt)
                this.send(this)
            },
            set: function (mode, accel, fs, fspd_filt) {
                this.payload.mode = mode
                this.payload.accel = accel
                this.payload.fs = fs
                this.payload.fspd_filt = fspd_filt
            },
            send: function () { platformInterface.send(this) }
        })

        // @command protection
        // @property ocp: int
        // @property ocp_en: int
        // @property ovp: int
        // @property ovp_en: int
        // @property fet_otp: int
        property var protection: ({
            "cmd": "protection",
            "payload": {
                "ocp": 0,
                "ocp_en": 0,
                "ovp": 0,
                "ovp_en": 0,
                "fet_otp": 0
            },
            update: function (ocp, ocp_en, ovp, ovp_en, fet_otp) {
                this.set(ocp, ocp_en, ovp, ovp_en, fet_otp)
                this.send(this)
            },
            set: function (ocp, ocp_en, ovp, ovp_en, fet_otp) {
                this.payload.ocp = ocp
                this.payload.ocp_en = ocp_en
                this.payload.ovp = ovp
                this.payload.ovp_en = ovp_en
                this.payload.fet_otp = fet_otp
            },
            send: function () { platformInterface.send(this) }
        })

        // @command run
        // @property value: int
        property var run: ({
            "cmd": "run",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command brake
        // @property value: int
        property var brake: ({
            "cmd": "brake",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command direction
        // @property value: int
        property var direction: ({
            "cmd": "direction",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command target_speed
        // @property value: double
        property var target_speed: ({
            "cmd": "target_speed",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command acceleration
        // @property value: double
        property var acceleration: ({
            "cmd": "acceleration",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command control_props
        property var control_props: ({
            "cmd": "control_props",
            update: function () {
                this.send(this)
            },
            send: function () { platformInterface.send(this) }
        })

    }
}
