/*
 * Copyright (c) 2018-2021 onsemi.
 *
 * All rights reserved. This software and/or documentation is licensed by onsemi under
 * limited terms and conditions. The terms and conditions pertaining to the software and/or
 * documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf (“onsemi Standard
 * Terms and Conditions of Sale, Section 8 Software”).
 */
import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/******************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-08-20 18:50:21.401 UTC-07:00
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias notifications: notifications
    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    QtObject {
        id: notifications

        // @notification: target_speed
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject target_speed: QtObject {
            property string caption: ""
            property string unit: ""
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: acceleration
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject acceleration: QtObject {
            property string caption: ""
            property string unit: ""
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 2
            }
        }

        // @notification: run
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject run: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: brake
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject brake: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: direction
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject direction: QtObject {
            property string caption: ""
            property string unit: ""
            property int value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: warning_1
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_1: QtObject {
            property string caption: "Warning 1"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_2
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_2: QtObject {
            property string caption: "Warning 2"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: warning_3
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-dynamic-sized
        property QtObject warning_3: QtObject {
            property string caption: "Warning 3"
            property string unit: ""
            property bool value: false
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: title
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject title: QtObject {
            property string caption: "Title"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: subtitle
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject subtitle: QtObject {
            property string caption: "Subtitle"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: actual_speed
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject actual_speed: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: board_temp
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject board_temp: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: input_voltage
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject input_voltage: QtObject {
            property string caption: "Caption"
            property string unit: "Unit"
            property double value: 0
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: status_log
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject status_log: QtObject {
            property string caption: "Status Log"
            property string unit: ""
            property string value: ""
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 1
            }
        }

        // @notification: toggle
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: bool
        // @property values: array-static-sized
        property QtObject toggle: QtObject {
            property string caption: "Toggle"
            property string unit: ""
            property bool value: true

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }

            // @property index_0: string
            // @property index_1: string
            property QtObject values: QtObject {
                objectName: "array"
                property string index_0: "True"
                property string index_1: "False"
            }
        }

        // @notification: slider
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject slider: QtObject {
            property string caption: "Slider"
            property string unit: "Unit"
            property int value: 2380
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 10000
                property int index_1: 0
                property int index_2: 10
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: infobox_integer
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-dynamic-sized
        property QtObject infobox_integer: QtObject {
            property string caption: "InfoBox Integer"
            property string unit: "Unit"
            property int value: 11
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: infobox_double
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: double
        // @property values: array-dynamic-sized
        property QtObject infobox_double: QtObject {
            property string caption: "InfoBox Double"
            property string unit: "Unit"
            property double value: 11.11
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: infobox_string
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: string
        // @property values: array-dynamic-sized
        property QtObject infobox_string: QtObject {
            property string caption: "InfoBox String"
            property string unit: "Unit"
            property string value: "Pass"
            property var values: []

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }
        }

        // @notification: combobox
        // @property caption: string
        // @property scales: array-static-sized
        // @property states: array-static-sized
        // @property unit: string
        // @property value: int
        // @property values: array-static-sized
        property QtObject combobox: QtObject {
            property string caption: "ComboBox"
            property string unit: ""
            property int value: 0

            signal notificationFinished()

            // @property index_0: int
            // @property index_1: int
            // @property index_2: int
            property QtObject scales: QtObject {
                objectName: "array"
                property int index_0: 0
                property int index_1: 0
                property int index_2: 0
            }

            // @property index_0: int
            property QtObject states: QtObject {
                objectName: "array"
                property int index_0: 0
            }

            // @property index_0: string
            // @property index_1: string
            // @property index_2: string
            property QtObject values: QtObject {
                objectName: "array"
                property string index_0: "Item 1"
                property string index_1: "Item 2"
                property string index_2: "Item 3"
            }
        }

        // @notification: advanced_view_tab
        // @property value: bool
        property QtObject advanced_view_tab: QtObject {
            property bool value: false

            signal notificationFinished()
        }

    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands
        // @command control_props
        property var control_props: ({
            "cmd": "control_props",
            update: function () {
                this.send(this)
            },
            send: function () { platformInterface.send(this) }
        })

        // @command run
        // @property value: bool
        property var run: ({
            "cmd": "run",
            "payload": {
                "value": false
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command brake
        // @property value: bool
        property var brake: ({
            "cmd": "brake",
            "payload": {
                "value": false
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command direction
        // @property value: bool
        property var direction: ({
            "cmd": "direction",
            "payload": {
                "value": true
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command target_speed
        // @property value: double
        property var target_speed: ({
            "cmd": "target_speed",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command acceleration
        // @property value: double
        property var acceleration: ({
            "cmd": "acceleration",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command toggle
        // @property value: bool
        property var toggle: ({
            "cmd": "toggle",
            "payload": {
                "value": true
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command slider
        // @property value: int
        property var slider: ({
            "cmd": "slider",
            "payload": {
                "value": 2380
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command infobox_integer
        // @property value: int
        property var infobox_integer: ({
            "cmd": "infobox_integer",
            "payload": {
                "value": 11
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command infobox_double
        // @property value: double
        property var infobox_double: ({
            "cmd": "infobox_double",
            "payload": {
                "value": 11.11
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command infobox_string
        // @property value: string
        property var infobox_string: ({
            "cmd": "infobox_string",
            "payload": {
                "value": "Pass"
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

        // @command combobox
        // @property value: int
        property var combobox: ({
            "cmd": "combobox",
            "payload": {
                "value": 0
            },
            update: function (value) {
                this.set(value)
                this.send(this)
            },
            set: function (value) {
                this.payload.value = value
            },
            send: function () { platformInterface.send(this) }
        })

    }
}
