import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/******************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-02-24 12:47:46.455 UTC-08:00
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    // -------------------------------------------------------------------
    // Incoming Notification Messages
    //

    //DC link voltage
    property var voltage: {
        "v_out": 10
    }

    //Phase current
    property var current: {
        "i_led": 1
    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands

        property var request_initial_values : ({
                "cmd" : "request_initial_values",
                "payload": {},

                update: function () {
                    this.send(this)
                },
                set: function () {
                },
                send: function () { platformInterface.send(this) },
                show: function () { platformInterface.show(this) }
            })

        // @command set_i_led
        // @property duty_cycle: double
        // @property status: bool
        property var set_i_led: ({
            "cmd": "set_i_led",
            "payload": {
                "current": 0.0,
                "status": false
            },
            update: function (current,status) {
                this.set(current,status)
                this.send(this)
            },
            set: function (current,status) {
                this.payload.current = current
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

        // @command save_i_led
        // @property duty_cycle: double
        // @property status: bool
        property var save_i_led: ({
            "cmd": "save_i_led",
            "payload": {
                "current": 0.0
            },
            update: function (current) {
                this.set(current)
                this.send(this)
            },
            set: function (current) {
                this.payload.current = current
            },
            send: function () { platformInterface.send(this) }
        })

        // @command set_v_out
        // @property duty_cycle: double
        // @property status: bool
        property var set_v_out: ({
            "cmd": "set_v_out",
            "payload": {
                "voltage": 0.0,
                "status": false
            },
            update: function (voltage,status) {
                this.set(voltage,status)
                this.send(this)
            },
            set: function (voltage,status) {
                this.payload.voltage = voltage
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

        // @command save_values
        // @property voltage: double
        // @property current: double
        property var save_values: ({
            "cmd": "save_v_out",
            "payload": {
                "voltage": 0.0,
                "current": 0.0
            },
            update: function (voltage, current) {
                this.set(voltage, current)
                this.send(this)
            },
            set: function (voltage, current) {
                this.payload.voltage = voltage
                this.payload.current = current
            },
            send: function () { platformInterface.send(this) }
        })

        // @command set_pwm3
        // @property duty_cycle: double
        // @property status: bool
        property var set_flash_pwm: ({
            "cmd": "set_flash_pwm",
            "payload": {
                "on_time": 0.0,
                "status": false
            },
            update: function (on_time,status) {
                this.set(on_time,status)
                this.send(this)
            },
            set: function (on_time,status) {
                this.payload.on_time = on_time
                this.payload.status = status
            },
            send: function () { platformInterface.send(this) }
        })

    }
}
